# Generated by Django 3.2.21 on 2023-10-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data describing a Category",
                verbose_name="Data",
            ),
        ),
    ]
