# Generated by Django 3.2.21 on 2023-10-13 07:54

from django.db import migrations, models
import django_extensions.db.fields
import tagulous.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0002_auto_20231013_0223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=True,
                help_text="The slug uniquely identifying the author. Generated automatically when field is left blank.",
                max_length=100,
                populate_from="name",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=True,
                help_text="The slug uniquely identifying the source. Generated automatically when field is left blank.",
                max_length=100,
                populate_from="name",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=True,
                help_text="The slug uniquely identifying the tag. Generated automatically when field is left blank.",
                max_length=100,
                populate_from="name",
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
